### ISSUE TITLE
Bug with last commit?

### ISSUE THREAD

**Issue by srfoster** [jeapostrophe/lux#9]
I had some working Lux code, but it has recently stopped working for me (possibly due to the most recent Lux commit?).  My code didn't change, which is why I suspect a bug.  If you need to reference what I'm doing with Lux, feel free to look at this (admittedly gross) file:

https://github.com/thoughtstem/game-engine/blob/master/game-entities.rkt

Below is the error I'm seeing.  It comes up a few frames after my game runs.  I've only been able to reproduce it on Linux so far.  (Still investigating.)

```
~r: contract violation
  expected: rational?
  given: +inf.0
  in: the 1st argument of
      (->*
       (rational?)
       (#:base
        (or/c
         (integer-in 2 36)
         (list/c 'up (integer-in 2 36)))
        #:format-exponent
        (or/c
         #f
         string?
         (-> exact-integer? string?))
        #:min-width
        exact-positive-integer?
        #:notation
        (or/c
         'positional
         'exponential
         (->
          rational?
          (or/c 'positional 'exponential)))
        #:pad-string
        non-empty-string?
        #:precision
        (or/c natural? (list/c '= natural?))
        #:sign
        (or/c
         #f
         '+
         '++
         'parens
         (list/c
          (or/c string? (list/c string? string?))
          (or/c string? (list/c string? string?))
          (or/c
           string?
           (list/c string? string?)))))
       string?)
  contract from: <collects>/racket/format.rkt
  blaming: <pkgs>/lux/word.rkt
   (assuming the contract is correct)
  at: <collects>/racket/format.rkt:63.2
```

**Comment by srfoster** [comment]
I lied / just remembered:  

One thing I did recently change was the default FPS from 60.0 to 30.0.  Not sure why that would affect things, but it does seem like the error above is at least kind of related to FPS display.

**Comment by jeapostrophe** [comment]
I believe I fixed the problem with the most recent commit. Can you see if I'm right?

For reference, what I changed was the way time between frames was calculated. Before, if you said you wanted 60FPS, it would guarantee a 16.6ms delay in between running your code. This isn't a good way to think about it, because it means that you can only get a 60FPS experience if your code takes 0ms to run. We really want to wait 16.6ms since the last frame ended. This has the potential downside of when your code always takes more that 16.6ms to run, you will never "recover" and never get any idleness.

**Comment by srfoster** [comment]
Thanks!  I'd like to test it, but I'm getting another weird error (again, on Linux only, I think).

This one is pretty weird and has no stacktrace:

```
Assertion #<procedure:negative?> failed on 0.0
```

It happens simply when I do:

```
(require lux)
```

I'm currently trying to track down the error myself.  I'll add more info as I get some.   But if you have some insights, please let me know. :)

**Comment by srfoster** [comment]
Update:

It's not lux, per se.  I get the same error with:

```
(require math/flonum)
```

**Comment by srfoster** [comment]
Update:

Nope.  It's not that simple either.  When I boot DrRacket fresh, and require `lux` or `math/flonum`, everything is fine.  But when I first:

```
(require game-engine)
```

Then (even if I delete that require!):

I get the above error on 

```
(require lux)
```

Or, more specifically:

```
(require math/flonum)
```

Rebooting DrRacket makes `lux` and `math/flonum` work again.

Incidentally, this is the same behavior I reported in this other ticket:

https://github.com/jbclements/RSound/issues/38

But at the time, I thought it was related to `rsound`.  In reality, it must be something weird that I'm doing in `game-engine`.   Still investigating that.

**Comment by srfoster** [comment]
Update:

It's not `game-engine` per se either.  I can get the same behavior with:

```
(require racket-chipmunk)
(require math/flonum)
```

...where `racket-chipmunk` is my package here:

https://github.com/thoughtstem/racket-chipmunk

This is a dependency of `game-engine`, which is why I blamed that package.  Looking into `racket-chipmunk` now...

**Comment by srfoster** [comment]
Okay, I've narrowed it down to the following (on Linux):

```
(require ffi/unsafe)
(define chipmunk (ffi-lib "./binaries/libchipmunk"))
```

After which, any attempt to:

```
(require math/flonum)
```

Fails with:

```
Assertion #<procedure:negative?> failed on 0.0
```

Backtrace gives only:

```
#<void>:#f:#f
```

I'm at a loss now. :(

I'm going to have to work around this issue by making `game-engine` dependent on the version of `lux` before the addition of `(require math/flonum)`.   

Maybe commit c3998a4?

**Comment by jeapostrophe** [comment]
I switched to `racket/math`. Tell me if that helps.

**Comment by srfoster** [comment]
Will do! Thanks.  I'm heading home for the day, but I'll do this first thing tomorrow morning.

**Comment by srfoster** [comment]
Yes!  That fixed the weirdness with `Assertion #<procedure:negative?> failed on 0.0` and also fixed the original issue with `~r: contract violation`.  I updated `game-engine` to depend on the latest `lux` commit.

Thanks!

Just curious, how might I gain more insight into the `Assertion #<procedure:negative?> failed on 0.0` problem?  It bewilders me.  Although it doesn't block me from using `lux` anymore, it does block me from using `rsound`.   I'd love to know if I've done something wrong, or if it's a bug in Racket or `math/flonum`, etc.

**Comment by jeapostrophe** [comment]
I think it is just an error in `math/flonum`'s use of Typed Racket. I seem to recall that library tries to do some clever stuff to be faster and it looks like it is broken on your system (although not mine or the test bot.)
